# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea957e6a2d817499499f991cc0530ce061b7f96a8da690c2824445505be21ec2a17860b0553e73aa5a72df069131ccbfa9e6f9e2884975500c7854de5c09d9f1
  godmin:
    user: godmin
    pass: godmin123

test:
  secret_key_base: 0d8003d9c466387e90ffbea3f495f0e5a54970c66d071f8cb4daccf5c0a7e89d48499839f281b1c65e939ffcb6fadc905f5bd0ec33c52ecabd6beb75995dd4b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  godmin:
    user: <%= ENV['GODMIN_USER'] %>
    pass: <%= ENV['GODMIN_PASS'] %>
